### ISSUE TITLE
egypt payment 

### ISSUE THREAD

**Issue by rectrick** [rowyio/buildship#1]
hi i like this builder but stripe dont support my cuntry so we need arabic payments method supported egypt and more arab countries over 2milion pepoles

**Comment by rectrick** [comment]
https://paymob.com/

> so we nee

https://paymob.com/

**Comment by bofeiw** [comment]
Hi, we use Stripe to handle payments. Stripe is widely supported, and it supports major payment methods like Visa or Master card.

If there is really no way for you to complete the BuildShip subscription payment, you can [send us a support message in BuildShip app](https://docs.buildship.com/support-messages), and we can provide alternative methods for you like Bitcoin.
